version: 2

models:
  - name: fact_reviews
    description: "Fact table capturing customer review events"

    columns:
      - name: review_id
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null

      - name: review_score
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5]

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - review_id
            - order_id