-- using the correct db and schema context
USE DATABASE ECOMMERCE_DWH;
USE SCHEMA RAW;

--copying data into ORDERS_RAW table from csv
COPY INTO ORDERS_RAW
FROM @RAW_STAGE/olist_orders_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM ORDERS_RAW;

SELECT COUNT(DISTINCT order_id) FROM ORDERS_RAW;

--copying data into CUSTOMERS_RAW table from csv
COPY INTO CUSTOMERS_RAW
FROM @RAW_STAGE/olist_customers_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM CUSTOMERS_RAW;

SELECT COUNT(DISTINCT customer_id) FROM CUSTOMERS_RAW;

SELECT COUNT(DISTINCT customer_unique_id) FROM CUSTOMERS_RAW;

--copying data into ORDER_ITEMS_RAW table from csv
COPY INTO ORDER_ITEMS_RAW
FROM @RAW_STAGE/olist_order_items_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM ORDER_ITEMS_RAW;

SELECT COUNT(DISTINCT order_id, order_item_id) FROM ORDER_ITEMS_RAW;

--copying data into ORDER_PAYMENTS_RAW table from csv
COPY INTO ORDER_PAYMENTS_RAW
FROM @RAW_STAGE/olist_order_payments_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM ORDER_PAYMENTS_RAW;

SELECT COUNT(DISTINCT order_id, payment_sequential) FROM ORDER_PAYMENTS_RAW;

--copying data into ORDER_REVIEWS_RAW table from csv
COPY INTO ORDER_REVIEWS_RAW
FROM @RAW_STAGE/olist_order_reviews_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM ORDER_REVIEWS_RAW;

SELECT COUNT(DISTINCT review_id, order_id) FROM ORDER_REVIEWS_RAW;

SELECT COUNT(DISTINCT review_id) FROM ORDER_REVIEWS_RAW;

--copying data into PRODUCTS_RAW table from csv
COPY INTO PRODUCTS_RAW
FROM @RAW_STAGE/olist_products_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM PRODUCTS_RAW;

SELECT COUNT(DISTINCT product_id) FROM PRODUCTS_RAW;

--copying data into SELLERS_RAW table from csv
COPY INTO SELLERS_RAW
FROM @RAW_STAGE/olist_sellers_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM SELLERS_RAW;

SELECT COUNT(DISTINCT seller_id) FROM SELLERS_RAW;

--copying data into GEOLOCATION_RAW table from csv
COPY INTO GEOLOCATION_RAW
FROM @RAW_STAGE/olist_geolocation_dataset.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM GEOLOCATION_RAW;

SELECT COUNT(DISTINCT GEOLOCATION_LAT, GEOLOCATION_LNG, GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_CITY, GEOLOCATION_STATE) FROM GEOLOCATION_RAW;

--copying data into CATEGORY_NAME_TRANSLATION table from csv
COPY INTO CATEGORY_NAME_TRANSLATION_RAW
FROM @RAW_STAGE/product_category_name_translation.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT COUNT(*) FROM CATEGORY_NAME_TRANSLATION_RAW;

SELECT COUNT(DISTINCT product_category_name) FROM CATEGORY_NAME_TRANSLATION_RAW;

SELECT COUNT(DISTINCT product_category_name_english) FROM CATEGORY_NAME_TRANSLATION_RAW;
